# Generated by Django 3.1.6 on 2021-02-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
