# Generated by Django 3.1.6 on 2021-02-06 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooking_recipes', '0002_auto_20210206_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='direction',
            name='step',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='IngredientDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_recipes.recipe')),
                ('size_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooking_recipes.measure')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='cooking_recipes.IngredientDetail', to='cooking_recipes.Ingredient'),
        ),
    ]
